### ISSUE TITLE
DISPLAY not set correctly

### ISSUE THREAD

**Issue by FlyingRatBull** [teeedubb/teeedubb-xbmc-repo#16]
Steam fails to launch on my Linux machine with the message, that no Window Manager is running. Upon inspection the failing bit of code in _steam-launch.sh_ is

`DP=$(w -hs | awk '{print $3}') && export DISPLAY=$DP`

On my machine `w -hs` outputs

```
username   tty1     :0               21:33  /bin/sh /usr/bin/startkde
username   pts/0    :0               21:15  kded5 [kdeinit5]                                      
username   pts/1    :0                0.00s w -hs
```

And therefore the resulting DISPLAY variable is

```
:0
:0
:0
```

which is incorrect and Steam is unable to connect to the display.
If the above line is replaced by

`DP=$(w -hs | head -n 1 | awk '{print $3}') && export DISPLAY=$DP`

to only use the first line of the result, the resulting DISPLAY variable is correct and Steam starts as expected.

**Comment by erikthered** [comment]
I had a similar issue where this check would fail if I had an ssh session open, here's the example output from `w -hs`:

```
erikn    tty1     :0               33:37  lxqt-session
erikn    pts/0    192.168.1.104     1.00s w -sh
erikn    pts/1    192.168.1.104    28:53  less /home/erikn/.config/autostart/kodi.desktop
```

**Comment by FlyingRatBull** [comment]
Is there a specific reason to set (and therefore potentially overwrite) the DISPLAY variable?
Maybe it would be appropriate to only set it when its not already set to a non empty value?

**Comment by tcrass** [comment]
Hi,

> Is there a specific reason to set (and therefore potentially overwrite) the DISPLAY variable?
> Maybe it would be appropriate to only set it when its not already set to a non empty value?

I agree -- yesterday (before stumbling over this issue report ;) I removed the whole `DP=$(w -hs | awk '{print $3}') && export DISPLAY=$DP` part from both `~/.kodi/addons/script.steam.launcher/resources/main.py` and `~/.kodi/addons/script.steam.launcher/resources/scripts/steam-launch.sh` (or its copy in `~/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh`, respectively) and -- tadaa! -- the steam launcher did work again! I reckon explicitly setting DISPLAY should rarely, if ever, be necessary since if the launcher gets launched from Kodi it should already be running in an X environment.

(BTW, changing the steam-launcher.sh script was necessary since otherwise the steam executable itself would complain about not being able to open the -- incorrectly set -- display.)

Here's what `w -hs` gave me when calling it from an xterm running in the same display as Kodi:

    mythtv   tty1     -                39.00s xterm
    mythtv   pts/0    2003:dd:f25:2d00  8:31  -bash
    mythtv   pts/1    :0                7.00s w -hs

In this case, even FlyingRedBull's `head -n 1` wouldn't be of any help...

Cheers --

Torsten

**Comment by teeedubb** [comment]
Thanks for reporting this and providiing feedback. This all came about because two fresh ubuntu 18.10 installs default to using :1 as the DISPLAY, and the script wouldnt run. I cant remeber why I originally set the DISPLAY variable in the script, but removing it allows it to launch on my machine too.

I'll update the script in the repo. Thanks

**Comment by teeedubb** [comment]
OK, should be all  fixed in the latest version.

**Comment by racer290** [comment]
I have encountered a similar problem on Manjaro KDE where the default.py script queries for windows. The output of `w -hs` does not contain the `DISPLAY`, which makes `wmctrl -l` fail because DISPLAY is incorrectly set. The script fails with an error message at that point and Steam will start. I have fixed this issue on my system by replacing `$DP`with `:0`, but that's not a very portable solution.

**Comment by teeedubb** [comment]
Hi,

Sorry about the late reply. 
I am going to target and test against the Linux OS recommended by Steam, which currently is Ubuntu LTS. One of Linux's strength is also its weakness and I dont have the time or resources to test against all distros out there and the addon allows for customisation of scripts to suit each system.

Though in saying that, I am more than happy to merge a better solution which allows for greater compatibility amongst distros.
