### ISSUE TITLE
"Play" doesnt work

### ISSUE THREAD

**Issue by Dinth** [teeedubb/teeedubb-xbmc-repo#19]
Version: 3.41

Issue: Im trying to run Steam launcher from my "Games" menu (Aeon MQ8 skin). The launcher automatically shows in "Game add-ons", but trying to run it brings "Failed to play game - This game isn't compatible with any available emulators". Opening a context menu and clicking "Play" also doesn't work - same error. Only going to Informations in context menu and clicking "Run" from there launches Steam. 
This is odd behaviour, it would suggest that "Game add-ons" is made to contain only actual emulator games, but other gaming addons installed on my setup (Internet Archive Game Launcher and Rom Collection Browser) are also showing up in Games->Game add-ons and work perfectly fine.

**Comment by teeedubb** [comment]
Sounds like the skin is launching the addon as an emulator... possibly because this is a script and RCB and IAGL are both plugins? I have removed the addon from the programs group a while ago on my personal machine, so it only shows up as a game, not a program as well and havent experienced any issues with launching the addon from the addon menu. I just tried from the dedicated games main menu entry in esutuary and it also launches fine. 

Any chance you can try with estuary to see if its skin related?

**Comment by mstreurman** [comment]
I am using the latest Kodi 19 Matrix with your Steam Launcher Addon and every skin I use gives me the error stated by Dinth. I can however do a "Run" command from the Addon menu to run it... this kind of defeats the purpose :(
